// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct PostgreSQL connection, not the Accelerate proxy URL.
    // DATABASE_URL_DIRECT is the raw pg connection; fall back to DATABASE_URL if absent.
    url: process.env["DATABASE_URL_DIRECT"] ?? process.env["DATABASE_URL"],
  },
});
