/**
 * Turns a ToolModule into the markdown tool list kept in the project-tracker-mcp skill.
 * Generated, never hand-edited: `npm run mcp:docs` rewrites it, and tests/mcp-toolkit.test.ts fails
 * if the committed file is out of date.
 */

import type { ZodRawShape, ZodType } from "zod";
import type { AnyTool, ToolModule } from "./toolkit";

function inputList(shape: ZodRawShape): string {
  const names = Object.entries(shape).map(([name, schema]) => `\`${name}\`${(schema as ZodType).isOptional() ? "" : "*"}`);
  return names.length ? names.join(", ") : "none";
}

function table(tools: AnyTool[]): string {
  const rows = tools.map((t) => `| \`${t.name}\` | ${t.description.replace(/\|/g, "\\|")} | ${inputList(t.input)} |`);
  return ["| Tool | What it does | Inputs (* required) |", "|---|---|---|", ...rows].join("\n");
}

export function renderToolsMarkdown(module: ToolModule, intro: string, values: string): string {
  const reads = module.tools.filter((t) => t.access === "read");
  const writes = module.tools.filter((t) => t.access === "write");
  return [
    `# ${module.name} MCP tools`,
    "",
    "<!-- Generated by `npm run mcp:docs` from the tool definitions. Do not edit by hand. -->",
    "",
    intro.trim(),
    "",
    "## Read",
    "",
    table(reads),
    "",
    "## Write",
    "",
    table(writes),
    "",
    "## Values",
    "",
    values.trim(),
    "",
  ].join("\n");
}
